version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: luaroncrew/foodgram:v1
    restart: always
    volumes:
      - ./staticfiles/:/code/assets/
    depends_on:
      - db
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles/:/code/assets
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: