
version: '3.8'

volumes:
  postgres_data:
  static:
  media:
  nginx_config:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: luaroncrew/foodgram:v1
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    volumes:
      - static:/code/assets
      - media:/code/media
      - nginx_config:/code/nginx/

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - 80:80
    volumes:
      - static:/code/assets
      - media:/code/media
      - nginx_config:/etc/nginx/conf.d/
    depends_on:
      - web
    restart: always
