version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    container_name: db
    restart: always
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    image: luaroncrew/foodgram:v1
    container_name: web
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - static:/code/assets
      - media:/code/media
    env_file:
      - .env

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    volumes:
    - static:/code/assets
    - media:/code/media
    - ./nginx:/etc/nginx/conf.d
    ports:
    - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media: