# Generated by Django 3.0.5 on 2021-03-13 07:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, 'ЗАВТРАК'), (2, 'ОБЕД'), (3, 'УЖИН')], max_length=15), size=None),
        ),
    ]
