# Generated by Django 3.0.5 on 2021-03-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210313_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[(1, 'ЗАВТРАК'), (2, 'ОБЕД'), (3, 'УЖИН')], max_length=10, unique=True),
        ),
    ]
