# Generated by Django 3.0.5 on 2021-03-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210313_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[('B', 'ЗАВТРАК'), ('L', 'ОБЕД'), ('D', 'УЖИН')], max_length=10, unique=True),
        ),
    ]
