# Generated by Django 3.0.5 on 2021-03-13 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210313_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('B', 'ЗАВТРАК'), ('L', 'ОБЕД'), ('D', 'УЖИН')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
