# Generated by Django 3.0.5 on 2021-03-25 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0016_auto_20210318_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'ингредиент в рецепте', 'verbose_name_plural': 'ингредиенты в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'избранное'},
        ),
        migrations.AlterModelOptions(
            name='following',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ингредиент и единица измерения', 'verbose_name_plural': 'нигредиенты и единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'список покупок'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'рецепт', 'verbose_name_plural': 'рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тэг', 'verbose_name_plural': 'тэги'},
        ),
        migrations.AlterField(
            model_name='component',
            name='qnt',
            field=models.PositiveIntegerField(verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='following',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='подписчик'),
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Tag', verbose_name='тэги'),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique in favourites'),
        ),
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('user', 'follower'), name='unique following'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique in wishlist'),
        ),
    ]
