# Generated by Django 3.0.5 on 2021-03-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20210325_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='qnt',
            new_name='quantity',
        ),
    ]
