# Generated by Django 3.0.5 on 2021-03-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20210325_1503'),
    ]

    operations = [
    ]
